app:
  base-path: /api/${app.api.version}
  api:
    version: ${APP_API_VERSION:v1}
  kafka:
    topics:
      user-deleted: ${KAFKA_TOPIC_USER_DELETED:user-deleted}

spring:
  config:
    import: "classpath:application-common.yml"
  application:
    name: user-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  jpa:
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:user_schema}

  flyway:
    default-schema: ${DB_SCHEMA:user_schema}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: user-deleted:city.pulse.user.event.UserDeletedEvent

server:
  port: ${APP_PORT:8084}

logging:
  level:
    org.apache.kafka: WARN
    org.springframework.kafka: WARN
