spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-service:8081/api/v1/auth/.well-known/jwks.json
          issuer-uri: http://auth-service:8081

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false