-- Legacy individual databases are no longer created.
-- We now use a single database 'city_pulse' (created by POSTGRES_DB env var)
-- with a Schema-Per-Service pattern managed automatically by Flyway.
