spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/auth_db
    username: dev_user
    password: dev_password

app:
  jwt:
    access-token-ttl-ms: 1000000
    refresh-token-ttl-ms: 604_800_000
    iss: http://auth-service:8081