spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/city_pulse
    username: dev_user
    password: dev_password

app:
  security:
    jwt:
      ttl:
        access-token-ttl: 15m
        refresh-token-ttl: 30d
        temporary-token-ttl: 10m
      active-key-id: key-1
      iss: http://auth-service:8081
      rotation: { }
