spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

app:
  jwt:
    access-token-ttl-ms: ${APP_JWT_ACCESS_TOKEN_TTL_MS}
    refresh-token-ttl-ms: ${APP_JWT_REFRESH_TOKEN_TTL_MS}
    iss: ${APP_JWT_ISSUER}