app:
  base-path: /api/${app.api.version}
  api:
    version: ${APP_API_VERSION:v1}
  security:
    jwt:
      ttl:
        access-token-ttl: ${JWT_ACCESS_TOKEN_TTL:15m}
        refresh-token-ttl: ${JWT_REFRESH_TOKEN_TTL:30d}
        temporary-token-ttl: ${JWT_TEMPORARY_TOKEN_TTL:10m}
      active-key-id: ${JWT_ACTIVE_KEY_ID:key-1}
      iss: ${JWT_ISSUER:http://auth-service:8081}
      rotation:
        key-1:
          private-key-path: ${JWT_PRIVATE_KEY_PATH}
          public-key-path: ${JWT_PUBLIC_KEY_PATH}

spring:
  config:
    import: "classpath:application-common.yml"
  application:
    name: auth-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH_GOOGLE_CLIENT_ID:notexists}
            client-secret: ${OAUTH_GOOGLE_CLIENT_SECRET:notexists}

  jpa:
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:auth_schema}

  flyway:
    default-schema: ${DB_SCHEMA:auth_schema}

server:
  port: ${APP_PORT:8081}

logging:
  level:
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR
