spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

app:
  security:
    jwt:
      ttl:
        access-token-ttl: ${JWT_ACCESS_TOKEN_TTL}
        refresh-token-ttl: ${JWT_REFRESH_TOKEN_TTL}
        temporary-token-ttl: ${JWT_TEMPORARY_TOKEN_TTL}
      active-key-id: key-1
      iss: ${JWT_ISSUER}
      rotation:
        key-1:
          private-key-path: ${JWT_PRIVATE_KEY_PATH}
          public-key-path: ${JWT_PUBLIC_KEY_PATH}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false