spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/post_db
    username: dev_user
    password: dev_password
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-service:8081/api/v1/auth/.well-known/jwks.json
          issuer-uri: http://auth-service:8081
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 12MB

gcp:
  project-id: ${GCP_PROJECT_ID}
  client-id: ${GCP_CLIENT_ID}
  private-key-id: ${GCP_PRIVATE_KEY_ID}
  private-key: ${GCP_PRIVATE_KEY}
  client-email: ${GCP_CLIENT_EMAIL}
  bucket:
    name: ${GCP_BUCKET_NAME}