app:
  base-path: /api/${app.api.version}
  api:
    version: ${APP_API_VERSION:v1}
  kafka:
    topics:
      file-deleted: ${KAFKA_TOPIC_FILE_DELETED:file-deleted}
      user-deleted: ${KAFKA_TOPIC_USER_DELETED:user-deleted}

spring:
  config:
    import: "classpath:application-common.yml"
  application:
    name: post-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    hikari:
      connection-init-sql: SET search_path TO ${DB_SCHEMA:post_schema}, extensions;

  jpa:
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:post_schema}

  flyway:
    default-schema: ${DB_SCHEMA:post_schema}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: file-deletion:city.pulse.post.event.FileDeleteRequestEvent
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:post-service-group}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.type.mapping: user-deleted:city.pulse.post.event.UserDeletedEvent
        spring.json.trusted.packages: "*"

server:
  port: ${APP_PORT:8082}


