app:
  api:
    version: v1
  base-path: /api/${app.api.version}

spring:
  application:
    name: storage-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 12MB

server:
  port: ${APP_PORT:8085}

storage:
  allowed-file-types:
    - image/jpeg
    - image/png
    - image/heic
    - image/heif
