spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/api/v1/.well-known/jwks.json

app:
  services:
    auth:
      url: http://localhost:8081/api/v1
    user:
      url: http://localhost:8084/api/v1
