app:
  services:
    auth:
      url: ${AUTH_SERVICE_URL}/api/v1
    registration:
      url: ${REGISTRATION_SERVICE_URL}/api/v1

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
