name: auth-service CI/CD

on:
  push:
    paths:
      - 'backend/auth-service/**'
      - 'backend/city-pulse-common/**'
      - 'backend/pom.xml'
      - '.github/workflows/auth-service-ci.yml'
      - '.github/workflows/common-service-ci.yml'
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  call-common-ci:
    uses: ./.github/workflows/common-service-ci.yml
    with:
      service_name: 'auth-service'
      service_path: 'backend/auth-service'
