name: city-pulse-common CI/CD

on:
  push:
    paths:
      - 'backend/city-pulse-common/**'
  workflow_dispatch:

jobs:
  build-test-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
          cache-dependency-path: 'backend/city-pulse-common/pom.xml'
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Publish to GitHub Packages
        run: mvn clean deploy -f backend/city-pulse-common/pom.xml -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
