name: mobile-bff-service CI/CD

on:
  push:
    paths:
      - 'backend/mobile-bff-service/**'
      - 'backend/city-pulse-common/**'
      - 'backend/pom.xml'
  release:
    types: [published]
  workflow_dispatch:

jobs:
  call-common-ci:
    uses: ./.github/workflows/common-service-ci.yml
    with:
      service_name: 'mobile-bff-service'
      service_path: 'backend/mobile-bff-service'
