name: post-service CI/CD

on:
  push:
    paths:
      - 'backend/post-service/**'
      - 'backend/city-pulse-common/**'
      - 'backend/pom.xml'
      - '.github/workflows/post-service-ci.yml'
      - '.github/workflows/common-service-ci.yml'
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  call-common-ci:
    uses: ./.github/workflows/common-service-ci.yml
    with:
      service_name: 'post-service'
      service_path: 'backend/post-service'
