name: storage-service CI/CD

on:
  push:
    paths:
      - 'backend/storage-service/**'
      - 'backend/city-pulse-common/**'
      - 'backend/pom.xml'
  release:
    types: [published]
  workflow_dispatch:

jobs:
  call-common-ci:
    uses: ./.github/workflows/common-service-ci.yml
    with:
      service_name: 'storage-service'
      service_path: 'backend/storage-service'
    secrets: inherit
